services:
  aidbox:
    image: healthsamurai/aidboxone:stable
    depends_on:
      - aidbox-db
    links:
      - "aidbox-db:database"
    ports:
      - "8080:8080"
    environment:
      PGHOST: database
      PGDATABASE: aidbox
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
    env_file:
      - ./env/aidbox
      - .env
    volumes:
      - ./resources:/resources
    healthcheck:
      interval: 1s
      timeout: 20s
      retries: 100
      test: curl --fail http://aidbox:8080/health || exit 1
  aidbox-db:
    image: "healthsamurai/aidboxdb:16.1"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidbox
  sdc:
    image: bedasoftware/fhir-sdc:1.0.0a17
    depends_on:
      aidbox:
        condition: service_healthy
    links:
      - aidbox
    env_file:
      - ./env/sdc
    tty: true
  fhir-converters-app:
    image: bedasoftware/aidbox-fhir-converter:main
    depends_on:
      aidbox:
        condition: service_healthy
    env_file:
      - ./env/fhir-converters-app
  build-seeds:
    image: bedasoftware/fhirsnake:latest
    command:
      - export
      - --output
      - /app/resources/initBundle.json
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
    depends_on:
      questionnaire-fce-fhir-converter:
        condition: service_healthy
    volumes:
      - ./resources/seeds:/app/resources
    env_file:
      - env/seeds
  watch-seeds:
    image: bedasoftware/fhirsnake:latest
    command:
      - watch
      - --external-fhir-server-url
      - http://root:secret@aidbox:8080
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
    volumes:
      - ./resources/seeds:/app/resources
    env_file:
      - env/seeds
    depends_on:
      questionnaire-fce-fhir-converter:
        condition: service_healthy
  questionnaire-fce-fhir-converter:
    image: bedasoftware/questionnaire-fce-fhir-converter:latest
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 5s
      timeout: 30s
      retries: 50
  sdc-ide:
    image: bedasoftware/sdc-ide:master
    depends_on:
      aidbox:
        condition: service_healthy
    ports:
      - "3001:5000"
    env_file:
      - ./env/sdc-ide
  jute:
    image: bedasoftware/jute-microservice:latest
    ports:
      - "8099:8090"
  fhirpath_mapping:
    image: bedasoftware/fhirpath-extract:0.2.0
    ports:
      - "8091:8090"
