---
apiVersion: v1
kind: Service
metadata:
  name: converter-simulator
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    workload: converter-simulator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: converter-simulator
  template:
    metadata:
      labels:
        workload: converter-simulator
    spec:
      containers:
      - name: converter-simulator
        image: bedasoftware/aidbox-fhir-converter:main
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128M"
          limits:
            memory: "256Gi"
        ports:
        - containerPort: 3000
        env:
        - name: AIDBOX_URL
          value: "http://aidbox-simulator-api:80"
        - name: APP_ID
          value: "converter"
        - name: APP_URL
          value: "http://converter-simulator:8081"
        - name: APP_PORT
          value: "3000"
        envFrom:
          - secretRef:
              name: converter-simulator
