---
apiVersion: v1
kind: Service
metadata:
  name: simulator
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    workload: simulator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: simulator
  template:
    metadata:
      labels:
        workload: simulator
    spec:
      containers:
      - name: simulator
        image: ghcr.io/kinnexus-au/simulator:0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512M"
          limits:
            memory: "512M"
        ports:
        - containerPort: 5000
