---
apiVersion: v1
kind: Service
metadata:
  name: simulator-sdc
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    workload: simulator-sdc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdc-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: sdc-simulator
  template:
    metadata:
      labels:
        workload: sdc-simulator
    spec:
      containers:
      - name: sdc-simulator
        image: bedasoftware/fhir-sdc:1.0.0a13
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500M"
          limits:
            memory: "1Gi"
        ports:
        - containerPort: 8081
        env:
        - name: APP_INIT_URL
          value: "http://aidbox-simulator-api:80"
        - name: APP_ID
          value: "sdc"
        - name: APP_URL
          value: "http://sdc-simulator:8081"
        - name: APP_PORT
          value: "8081"
        - name: AIO_PORT
          value: "8081"
        - name: AIO_HOST
          value: "0.0.0.0"
        - name: CREATE_MANIFEST_ATTRS
          value: "False"
        - name: CONSTRAINT_LEGACY_BEHAVIOR
          value: "False"
        - name: FHIRPATH_MAPPING_SERVICE
          value: fpml
        envFrom:
          - secretRef:
              name: simulator-sdc
