apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: simulator
  template:
    metadata:
      labels:
        workload: simulator
    spec:
      containers:
      - name: simulator
        image: ghcr.io/kinnexus-au/simulator:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512M"
          limits:
            memory: "512M"
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: simulator
